### ISSUE TITLE
Does it work with non default Spark versions?

### ISSUE THREAD

**Issue by shukapoo** [ispras/spark-openstack#18]
Launching Spark Cluster works perfectly fine with default spark version(1.6.1) but whenever I provide custom Spark version (For ex. 2.2.0 or 2.0.2) VMs of Spark cluster are set up but Spark Cluster doesn't come up. There is no visible error in the execution of playbook.  
On looking at logs on the master node I get attached errors. I think playbook is not able to turn up Master and/or Worker nodes when custom Spark version is used. 
![master_log](https://user-images.githubusercontent.com/31004156/33140893-144e6f42-cfba-11e7-96c9-ccd68a9ac637.png)

**Comment by al-indigo** [comment]
@shukapoo this sounds quite strange since we use version 2.2.0 ourselves. Check please your command line options; here's our version just for reference:

`./spark-openstack -k borisenko -i ~/.ssh/borisenko.key -s 8 -m spark.xlarge -t spark.2xlarge -a d2183c79-40f9-4106-9a55-cdbc3833d8ce -n computations-net -f ispras launch borisenko-cluster --spark-version 2.2.0 --spark-worker-mem-mb 32000`

**Comment by shukapoo** [comment]
Ok, then might be there is some problem with my cloud's namespace resolution. Actually, these playbooks were running master at spark//master_hostname:7077 (for non 1.6.2 versions) and spark master and slaves were not able to resolve that master_hostname.
It was bit strange that even adding the hostname to /etc/hosts things were not working.

I then changed spark-env.sh.j2 and added export SPARK_MASTER_HOST="{{ active_master_ip }}" this makes slaves to access spark master.
